#!/usr/bin/ksh -p
# Copyright (c) 2012 Espix Network, all right reserved
#

# Load SMF constants and functions
. /lib/svc/share/smf_include.sh

RPATH=spxopsd/rpath
OPTS=spxopsd/opts
PHPBIN=/usr/bin/php

if [[ -z "$SMF_FMRI" ]]; then
	echo "this script can only be invoked by smf(5)"
	exit $SMF_EXIT_ERR_NOSMF
fi

case "$1" in
'start')
	# Handles spxopsd startup
	rpath=$(svcprop -p ${RPATH} $SMF_FMRI)
	if [[ $? -ne 0 ]]; then
		echo "service property ${RPATH} file not defined for" \
		    "service: $SMF_FMRI"
		exit $SMF_EXIT_ERR_CONFIG
	fi

        opts=$(svcprop -p ${OPTS} $SMF_FMRI)
        if [[ $? -ne 0 ]]; then
                echo "service property ${OPTS} not defined for" \
                    "service: $SMF_FMRI"
                exit $SMF_EXIT_ERR_CONFIG
        fi


        if [ -z "${rpath}" -o ! -d ${rpath} ]; then
        	echo "rpath defined does not exist for" \
		    "service: $SMF_FMRI"
		exit $SMF_EXIT_ERR_CONFIG
        fi

        cd ${rpath}/sbin;
        cmd="./spxopsd ${opts}";
	echo $cmd;
	exec $cmd
	;;

'stop')
	POLITE=10
	smf_kill_contract $2 TERM 1 $POLITE
        ret=$?
	# '2' indicates timeout with non-empty contract.
        if [[ $ret -eq 2 ]]; then
	     smf_kill_contract $2 KILL 1 1
	     if [[ $ret -ne 0 ]]; then
                 exit $SMF_EXIT_ERR_FATAL
             fi
        fi
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit $SMF_EXIT_ERR_CONFIG
	;;

esac
exit $SMF_EXIT_OK
